version: v1
source_taxonomy: VisDrone
labels:
  - id: 1
    name: pedestrian
  - id: 2
    name: person
  - id: 3
    name: bicycle
  - id: 4
    name: car
  - id: 5
    name: van
  - id: 6
    name: truck
  - id: 7
    name: tricycle
  - id: 8
    name: awning-tricycle
  - id: 9
    name: bus
  - id: 10
    name: motor

